SeattleEnergySite/SeattleEnergySite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('plots/', include('plots.urls')),
]

SeattleEnergySite/plots/urls.py
from django.urls import path

from . import views

app_name = 'plots'
urlpatterns = [
    path('', views.index, name='index'),
]

SeattleEnergySite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

SeattleEnergySite/plots/models.py
from django.db import models

# Create your models here.

class Building(models.Model):
    year = models.IntegerField(default=2016)
    Major = models.IntegerField()
    Minor = models.IntegerField()
    BldgNbr = models.IntegerField()
    Address = models.CharField(max_length=200)
    main_use = models.CharField(max_length=20)
    Number_of_Stories = models.IntegerField(default=1)
    Construction_Class = models.IntegerField()
    Year_built = models.IntegerField()
    Year_remodeled = models.IntegerField()
    Heating_System = models.IntegerField()
    Elevators = models.BooleanField()
    Tax_PIN = models.IntegerField()
    No_parking_gfa = models.FloatField()
    Property_Name = models.CharField(max_length=200)
    lat = models.FloatField(default=47.6)
    longitude = models.FloatField(default=-122.3)
    Site_Energy_kbtu = models.FloatField()
    Electricity_kwh = models.FloatField()
    Electricity_kbtu = models.FloatField()
    Natural_Gas_kbtu = models.FloatField()
    Steam_kbtu = models.FloatField()
    site_eui = models.FloatField()

    def __str__(self):
        return self.Property_Name+' '+str(self.year)


class ASHRAE_target(models.Model):
    main_use = models.CharField(max_length=20)
    target = models.IntegerField()

    def __str__(self):
        return self.main_use

class Ecotope_target(models.Model):
    main_use = models.CharField(max_length=20)
    target = models.IntegerField()

    def __str__(self):
        return self.main_use

class Lookup(models.Model):
    case = models.CharField(max_length=20)
    code = models.IntegerField()
    value = models.CharField(max_length=20)

    def __str__(self):
        return self.value

SeattleEnergySite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

SeattleEnergySite/plots/views.py
from django.shortcuts import render
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt, mpld3, numpy as np, pdb
import matplotlib.colors as colors

from .models import Building, ASHRAE_target, Lookup, Ecotope_target
# Create your views here.

# From Joe Kington: This one gives two different linear ramps:
class MidpointNormalize(colors.Normalize):
    def __init__(self, vmin=None, vmax=None, midpoint=None, clip=False):
        self.midpoint = midpoint
        colors.Normalize.__init__(self, vmin, vmax, clip)

    def __call__(self, value, clip=None):
        # I'm ignoring masked values and all kinds of edge cases to make a
        # simple example...
        x, y = [self.vmin, self.midpoint, self.vmax], [0, 0.5, 1]
        return np.ma.masked_array(np.interp(value, x, y))

def index(request):
    try:
        b_use = request.POST['building_use']
        plot_type = request.POST['property']
        colorby = request.POST['colorby']
        year = int(request.POST['year'])
    except:
        b_use = 'Office'
        plot_type = 'Year_remodeled'
        colorby = 'site_eui'
        year = 2016
    b_objs = Building.objects.filter(main_use=b_use,year=year)
    b_euis=np.array(b_objs.values_list('site_eui',flat=True))
    plot_type_values = b_objs.values_list(plot_type,flat=True)
    color_vals = b_objs.values_list(colorby,flat=True)

    try:
        ashrae=True
        ash_targ = ASHRAE_target.objects.filter(main_use=b_use)
        targ_eui = ash_targ.values_list('target',flat=True)[0]
    except:
        ashrae=False
    
    try:
        ecotope=True
        eco_targ = Ecotope_target.objects.filter(main_use=b_use)
        eco_targ_eui = eco_targ.values_list('target',flat=True)[0]
    except:
        ecotope=False
    
    med_eui = np.median(b_euis)
    labels=["<p style='background-color:white'>"+
            '<br>'.join([n.title(),f'GFA: {a:.0f}',f'EUI: {eui:.1f}'])+'</p>' 
            for n,a,eui in b_objs.values_list('Property_Name',
                                      'No_parking_gfa','site_eui')]

    f,ax=plt.subplots()
    f.subplots_adjust(left=0.15,bottom=0.12)
    matplotlib.rc('font',size=18)
    the_cm = plt.get_cmap('plasma')
    if plot_type=='site_eui':
        # make histogram
        hist_max=np.min([np.max(b_euis),5*med_eui])
        ax.hist(b_euis,bins=20,range=[0,hist_max])
    else:
        scatter = ax.scatter(plot_type_values,b_euis,c=color_vals,cmap=the_cm,
                             norm=MidpointNormalize(
                midpoint=np.median(color_vals)))

    xlim=ax.get_xlim()
    ylim=ax.get_ylim()
    ax.set_xlim(xlim)
    ax.set_ylim(ylim)

    if plot_type=='site_eui':
        # target and median EUI lines are vertical in this case
        if ashrae:
            ax.plot([targ_eui,targ_eui],ylim,'k--',
                    label='ASHRAE target: %.1f'%(targ_eui))
        if ecotope:
            ax.plot([eco_targ_eui,eco_targ_eui],ylim,'k--',
                    label='Ecotope 2050 S2 target: %.1f'%(eco_targ_eui))

        ax.plot([med_eui,med_eui],ylim,'C1:',
                label=str(year)+' Median: %.1f'%(med_eui))
        ax.legend(loc=1)
    else:
        # make scatter plot clickable and have labels
        targets = ["http://blue.kingcounty.com/Assessor/eRealProperty/Detail.aspx?ParcelNbr="+f"{t:010}" for t in b_objs.values_list('Tax_PIN',flat=True)]
        tooltip = mpld3.plugins.PointHTMLTooltip(scatter,labels,
                                                 targets=targets)
        mpld3.plugins.connect(f,tooltip)
        if ashrae:
            ax.plot(xlim,[targ_eui,targ_eui],'k--',
                    label='ASHRAE target: %.1f'%(targ_eui))
        if ecotope:
            ax.plot(xlim,[eco_targ_eui,eco_targ_eui],'g-.',
                    label='Ecotope 2050 S2 target: %.1f'%(eco_targ_eui))
        ax.plot(xlim,[med_eui,med_eui],'C0:',
                label=str(year)+' Median: %.1f'%(med_eui))
        ax.set_ylabel('Energy Usage Intensity (EUI) [kBTU / sq ft / year]',fontsize=18)
        ax.legend(loc=2)


    if plot_type in Lookup.objects.values_list('case',flat=True).distinct():
        # print text for x labels
        case_objs=Lookup.objects.filter(case=plot_type)
        plt.xticks(case_objs.values_list('code',flat=True),
                   case_objs.values_list('value',flat=True))

    ax.set_xlabel(plot_type,fontsize=18)
    ax.tick_params(axis='both',which='major',labelsize=18)

    js_plot = mpld3.fig_to_html(f)

    uses = Building.objects.values_list('main_use',flat=True).distinct()
    years = Building.objects.values_list('year',flat=True).distinct()
    plot_types = [f.name for f in Building._meta.get_fields() if f.get_internal_type() is not 'CharField']
    latlon = b_objs.values_list('lat','longitude')

    mn = MidpointNormalize(vmin=np.min(color_vals),vmax=np.max(color_vals),
                           midpoint=np.median(color_vals))
    orig_c = the_cm(mn(color_vals))
    colors = (orig_c[:,:3]*256).astype(int)
    colors = map(tuple, colors)

    context = {'js_plot': js_plot, 'building_uses':uses,'sel_year':year,
               'plots':plot_types,'selected_use':b_use, 'colors':colors,
               'selected_plot':plot_type, 'selected_cb':colorby,
               'latlon':latlon,'years':years}
    return render(request, 'plots/index.html', context)

SeattleEnergySite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import Question, Choice

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

SeattleEnergySite/polls/templates/plots/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
   <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.4.3/css/ol.css" type="text/css">-->
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.4.3/build/ol.js"></script>
    <style>
      .map {
        height: 600px;
        width: 600px;
      }
    </style>
    
    <title>Seattle Building Energy Data</title>
  </head>
  <body>
    <h1>{{ selected }}</h1>
    <form action="{% url 'plots:index' %}" method="post">
    <table><tr>
	<td>
      {% csrf_token %}
      Year:
      <select name="year" onchange="this.form.submit()"> 
	{% for year in years %}
	<option value="{{ year }}" {% if year == sel_year %} selected{% endif %}>{{ year }}</option>
	{% endfor %}
      </select>
      <br>
      Predominant building use type:
      <select name="building_use" onchange="this.form.submit()"> 
	{% for use in building_uses %}
	<option value="{{ use }}" {% if use == selected_use %} selected{% endif %}>{{ use }}</option>
	{% endfor %}
      </select>

      {{ js_plot|safe }}
      
      Use
      <select name="property" onchange="this.form.submit()">
	{% for plot in plots %}
	<option value="{{ plot }}" {% if plot == selected_plot %} selected{% endif %}>{{ plot }}</option>
	{% endfor %}
      </select>
      for x-axis
      <br>
      Color plot and map points using:
      <select name="colorby" onchange="this.form.submit()">
	{% for color_by in plots %}
	<option value="{{ color_by }}" {% if color_by == selected_cb %} selected{% endif %}>{{ color_by }}</option>
	{% endfor %}
      </select>
    </td>

	<td style="width:600px">
    <div id="map" class="map"></div>
    <script type="text/javascript">
      var layer = new ol.layer.Tile({
        source: new ol.source.OSM()
      });
      var center = ol.proj.fromLonLat([-122.35 , 47.63]);

      var fill = new ol.style.Fill({color: 'blue'});
      var stroke = new ol.style.Stroke({color: 'blue', width:0.25});
      var style = new ol.style.Style({
          image: new ol.style.Circle({
            fill: fill,
            stroke: stroke,
            radius: 5
            }),
          fill: fill,
          stroke: stroke
          });

      var features = new Array(); 

      {% for lat,lon in latlon %}
      features.push(new ol.Feature(new ol.geom.Point(ol.proj.fromLonLat([{{lon}}, {{lat}}])) ) );
      {% endfor %}

      var source = new ol.source.Vector({features: features });

      var vectorLayer = new ol.layer.Vector({source: source});

      {% for col in colors %}
      features[{{ forloop.counter0 }}].setStyle(new ol.style.Style({
          image: new ol.style.Circle({
            fill: new ol.style.Fill({color: 'rgb{{ col }}'}),
            stroke: new ol.style.Stroke({color: 'rgb{{ col }}', width:0.25}),
            radius: 5}) }));
      {% endfor %}

      var map = new ol.Map({
        target: "map",
        layers: [layer, vectorLayer],
        view:  new ol.View({
          center: center, 
          zoom:12
        })
      });
    </script>
    </div>
    </td>
    </tr>
   </table>
   </form>
  </body>
</html>